assignment_1_simple_cms_blueprint/config/routes.rb
Rails.application.routes.draw do


  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  root 'public#about_us'

  get 'public/contact_us'
  get 'access/menu'
  get 'access/login'
  get 'access/logout'
  post 'access/attempt_login'

  resources :subjects do
    member do
      get :delete
    end
  end

#By default delete route is not included , to include it we have to do this
  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get 'delete'
    end
  end

  resources :admin_users , except: [:show] do
    member do
      get 'delete'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

assignment_1_simple_cms_blueprint/app/views/pages/_form.html.erb
<!-- PARTIAL name always start with underscore '_' -->
<%= show_error_message(f.object) %> <br/>
<table>
  <tr>
    <th>Page Name</th>
    <td><%= f.text_field(:name) %> </td>
  </tr>
  <tr>
    <th>Subject Id</th>
    <td><%= f.select(:subject_id, @subjects_lookup) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@pages_count) %></td>
  </tr>
  <tr>
    <th>Permalink</th>
    <td><%= f.text_field(:permalink) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
</table>

assignment_1_simple_cms_blueprint/app/views/pages/delete.html.erb
<div class="delete-confirmation">
  <h2>Delete confirmation:</h2>
  <%= form_for(@page,url: page_path(@page, subject_id: @subject.id) , method:"delete") do |f|%>
  <p> Are you sure you want to delete? </p>
  <div> <%= f.submit("Delete page") %> </div>
  <% end %>
</div>

assignment_1_simple_cms_blueprint/app/views/pages/edit.html.erb
<h1>Edit Page</h1>

<%= form_for(@page, url: page_path(@page, subject_id: @subject.id)) do |f| %>
<%= render(partial:'form', locals: {f: f}) %>
<div class="form-buttons">
  <%= f.submit("Update Page") %>
</div>
<% end %>

<div class="action index">
  <br/>
<%= link_to("Back to pages", pages_path(subject_id: @subject.id)) %>
</div>

assignment_1_simple_cms_blueprint/app/views/pages/index.html.erb
<h1>All Pages</h1>
<br/>

<table>
  <tr>
    <th>Sr No.</th>
    <th>Subject id</th>
    <th>Page Name</th>
    <th>Permalink</th>
    <th>Position</th>
    <th>Visible</th>
    <th>Actions</th>
  </tr>
  <% @pages.each do |page| %>
  <tr>
    <td><%=page.id %></td>
    <td><%= link_to(page.subject_id, subject_path(page.subject_id)) %></td>
    <td><%=page.name %></td>
    <td><%=page.permalink %></td>
    <td><%=page.position %></td>
    <td><%=page.visible ? "Yes" : "No"  %></td>
    <td>
      <%= link_to("View Sections", sections_path(page_id: page.id)) %> ||
      <%= link_to('Show', page_path(page, subject_id: @subject.id)) %> ||
      <%= link_to('Edit', edit_page_path(page, subject_id: @subject.id)) %> ||
      <%= link_to('Delete', delete_page_path(page, subject_id: @subject.id)) %></td>
  </tr>
    <% end %>
</table>
<br/>
<div class="action new">
  <%= link_to("Create New Page",new_page_path(subject_id: @subject.id)) %>
</div>
<br/>
<div class="action subjects">
  <%= link_to("Back to Subjects",subjects_path(subject_id: @subject.id)) %>
</div>

assignment_1_simple_cms_blueprint/app/views/pages/new.html.erb
<h1>Create new Page</h1>

<%= form_for(@page, url: pages_path(subject_id: @subject.id)) do |f| %>

<!-- Adding a partial here: Also in partial we have a variable "f" , that value we need to pass on from here in "locals" hash  -->
<%= render(partial:'form', locals: { f: f } ) %>

<div class="form-buttons">
  <%= f.submit("Create Page") %>
</div>
<% end %>

<div class="action index">
  <br/>
<%= link_to("Back to pages", pages_path(subject_id: @subject.id))%>
</div>

assignment_1_simple_cms_blueprint/app/views/pages/show.html.erb
<h1>Show Page: <%= @page.name %></h1>

<table>
  <tr>
    <th>Page Name</th>
    <td><%= @page.name %> </td>
  </tr>
  <tr>
    <th>Subject Id</th>
    <td><%= @page.subject_id %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= @page.position %></td>
  </tr>
  <tr>
    <th>Permalink</th>
    <td><%= @page.permalink %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= @page.visible %></td>
  </tr>
</table>


<div class="action index">
  <br/>
<%= link_to("Back to pages", pages_path(subject_id: @subject.id)) %>
</div>