assignment_1_simple_cms_blueprint/config/routes.rb
Rails.application.routes.draw do


  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  root 'public#about_us'

  get 'public/contact_us'
  get 'access/menu'
  get 'access/login'
  get 'access/logout'
  post 'access/attempt_login'

  resources :subjects do
    member do
      get :delete
    end
  end

#By default delete route is not included , to include it we have to do this
  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get 'delete'
    end
  end

  resources :admin_users , except: [:show] do
    member do
      get 'delete'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

assignment_1_simple_cms_blueprint/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  has_secure_password

#MANY to MANY relation:(Simple)
  has_and_belongs_to_many :pages

#MANY TO MANY : (RICH FORMAT)
  has_many :section_edits
  has_many :sections, through: :section_edits

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
  FORBIDDEN_USERNAMES = ['littlebopeep','humptydumpty','marymary']

  scope :sorted, lambda { order('last_name, first_name ASC') }

  # "long form" validations
  # validates_presence_of :first_name
  # validates_length_of :first_name, :maximum => 25
  # validates_presence_of :last_name
  # validates_length_of :last_name, :maximum => 50
  # validates_presence_of :username
  # validates_length_of :username, :within => 8..25
  # validates_uniqueness_of :username
  # validates_presence_of :email
  # validates_length_of :email, :maximum => 100
  # validates_format_of :email, :with => EMAIL_REGEX
  # validates_confirmation_of :email

  # "sexy" validations:
  validates :first_name, presence: true,
                         length: { maximum: 25 }

  validates :last_name, presence: true,
                        length: { maximum: 25 }

  validates :username, length: { within: 8..25 },
                       uniqueness: true
  #
  # validates :email, presence: true,
  #                 length: { maximum: 100 },
  #                 format: EMAIL_REGEX,
  #                 confirmation: true

  validate :not_allowed_usernames

  def name
    first_name + " " + last_name
  end

  private

  def not_allowed_usernames
    if FORBIDDEN_USERNAMES.include? self.username
      self.errors.add(:username, "Forbidden")
    end
  end
end

assignment_1_simple_cms_blueprint/app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  layout 'navbar'
  before_action :confirm_logged_in, except:[:new, :create]

  def index
    @admin_users = AdminUser.sorted
  end

  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.new(admin_params)
    if @admin_user.save
      flash[:message] = "User created succesfully!!"
      redirect_to(admin_users_path) if session[:user_id]
      redirect_to(root_path)
    else
      render('new')
    end
  end

  def edit
    @admin_user = AdminUser.find(params[:id])
  end

  def update
    @admin_user = AdminUser.find(params[:id])
    if @admin_user.update(admin_params)
      flash[:message] = "User updated succesfully!!"
      redirect_to(admin_users_path)
    else
      render('edit')
    end
  end

  def delete
    @admin_user = AdminUser.find(params[:id])
  end

  def destroy
    @admin_user = AdminUser.find(params[:id])
    if @admin_user.destroy
      flash[:message] = "User entry deleted successfully!"
      redirect_to(admin_users_path)
    else
      flash.now[:message] = "Something went wrong!"
      render('delete')
    end
  end

  def admin_params
    params.require(:admin_user).permit(
      :username,
      :first_name,
      :last_name,
      :password)
  end
end

assignment_1_simple_cms_blueprint/app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

assignment_1_simple_cms_blueprint/app/views/admin_users/_form.html.erb
<table>
  <tr>
    <th> User Name: </th>
    <td><%= f.text_field(:username) %></td>
  </tr>
  <tr>
    <th> First Name: </th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th> Last Name: </th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th> Password: </th>
    <td><%= f.password_field(:password) %></td>
  </tr>
</table>

assignment_1_simple_cms_blueprint/app/views/admin_users/delete.html.erb
<div class="delete-confirmation">
  <h2>Delete confirmation:</h2>
  <%= form_for(@admin_user, method:"delete") do |f|%>
  <p> Are you sure you want to delete? </p>
  <div> <%= f.submit("Delete user") %> </div>
  <% end %>
</div>

assignment_1_simple_cms_blueprint/app/views/admin_users/edit.html.erb
<h1>Edit: <%= @admin_user.username %></h1>

<%= form_for(@admin_user) do |f| %>
<%= render(partial:'form', locals: { f: f } ) %>
<div class="form-buttons">
  <%= f.submit("Update") %>
</div>
<% end %>

assignment_1_simple_cms_blueprint/app/views/admin_users/index.html.erb
<h1>AdminUsers List:</h1>
<div>Total : <%= pluralize(@admin_users.size, 'admin user') %></div>
<table>
  <tr>
    <th>Username</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Actions</th>
  </tr>
<% @admin_users.each do |admin_user| %>
<tr>
  <td><%= admin_user.username %></td>
  <td><%= admin_user.first_name %></td>
  <td><%= admin_user.last_name %></td>
  <td><%= link_to("Edit", edit_admin_user_path(admin_user))%>
    <%= link_to("Delete", delete_admin_user_path(admin_user))%>
  </td>
</tr>
<% end %>
</table>
<br/>
<div class="create admin_user">
  <%= link_to("Create new AdminUser",new_admin_user_path) %>
</div>

assignment_1_simple_cms_blueprint/app/views/admin_users/new.html.erb
<h1> Please enter required details:</h1>
<br/>
<%= form_for(@admin_user) do |f| %>
<%= render(partial:'form', locals: { f: f } ) %>
<br/>
<div class="form-buttons">
  <%= f.submit("Create") %>
</div>
<% end %>
<br/>
<% if(session[:user_id]) %>
<div class="link">
  <%= link_to("Back to AdminUsers",admin_users_path) %>
</div>
<% end %>