assignment_1_simple_cms_blueprint/config/routes.rb
Rails.application.routes.draw do


  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  root 'public#about_us'

  get 'public/contact_us'
  get 'access/menu'
  get 'access/login'
  get 'access/logout'
  post 'access/attempt_login'

  resources :subjects do
    member do
      get :delete
    end
  end

#By default delete route is not included , to include it we have to do this
  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get 'delete'
    end
  end

  resources :admin_users , except: [:show] do
    member do
      get 'delete'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

assignment_1_simple_cms_blueprint/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :page
  has_many :section_edits
  has_many :admin_users, through: :section_edits
  #Since,AdminUser and Sections dont have direct relation but they are linked via SectionEdits
  # this will enable: AdminUser.sections will return associated sections
  scope :sorted, lambda { order('id ASC') }
  scope :invisible, -> { where( visible: false) }

  CONTENT_TYPES = ["Mythology", "Science", "History", "Architecture", "Science","Mathematics"].freeze

  validates_presence_of :name
  validates_length_of :name, maximum: 255

  validates_inclusion_of :content_type, in: CONTENT_TYPES, message: "Must be one of: #{CONTENT_TYPES.join(', ')}"
  validates_presence_of :content
end

assignment_1_simple_cms_blueprint/app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  layout('navbar')
  before_action :find_page
  before_action :confirm_logged_in

  def index
    @sections = @page.sections.sorted
  end

  def new
    @section = Section.new(visible: false, page_id: @page.id)
    @sections_count = Section.count + 1
    @pages_lookup = Page.all.map { |p| [p.name, p.id]}
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:message] = "Section created successfully!!"
      redirect_to(sections_path(page_id: @page.id))
    else
      @sections_count = Section.count + 1
      @pages_lookup = Page.all.map { |p| [p.name, p.id]}
      render('new')
    end
  end

  def show
    @section = Section.find(params[:id])
  end

  def edit
    @section = Section.find(params[:id])
    @sections_count = Section.count
    @pages_lookup = Page.all.map { |p| [p.name, p.id]}
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      flash[:message] = "Section updated successfully!!"
      redirect_to(section_path(@section, page_id:@page.id))
    else
      @sections_count = Section.count
      @pages_lookup = Page.all.map { |p| [p.name, p.id]}
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
    render('delete')
  end

  def destroy
    @section = Section.find(params[:id])
    if @section.destroy
      flash[:message] = "Section deleted successfully!!"
      redirect_to(sections_path(page_id: @page.id))
    else
      render('delete')
    end
  end

  def section_params
    params.require(:section).permit(
      :name,
      :page_id,
      :position,
      :visible,
      :content_type,
      :content)
  end

  private
  def find_page
    @page = Page.find(params[:page_id])
  end
end

assignment_1_simple_cms_blueprint/app/helpers/sections_helper.rb
module SectionsHelper
end

assignment_1_simple_cms_blueprint/app/views/sections/_form.html.erb
<table>
  <tr>
    <th>Section Name</th>
    <td><%= f.text_field(:name) %> </td>
  </tr>
  <tr>
    <th>Page Id</th>
    <td><%= f.select(:page_id, @pages_lookup) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@sections_count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Content Type</th>
    <td><%= f.select(:content_type, ["Mythology", "Science", "History", "Architecture", "Science","Mathematics"]) %></td>
  </tr>
  <tr>
    <th>Content</th>
    <td><%= f.text_area(:content, size:"50x10") %></td>
  </tr>
</table>

assignment_1_simple_cms_blueprint/app/views/sections/delete.html.erb
<div class="delete-confirmation">
  <h2>Delete confirmation:</h2>
  <%= form_for(@section, url: section_path(@section, page_id: @page.id), method:"delete") do |f|%>
  <p> Are you sure you want to delete? </p>
  <div> <%= f.submit("Delete Section") %> </div>
  <% end %>
</div>

assignment_1_simple_cms_blueprint/app/views/sections/edit.html.erb
<h1>Update Section</h1>

<%= form_for(@section, url: section_path(@section, page_id: @page.id)) do |f| %>
<%= render(partial: 'form', locals: {f: f}) %>
<div class="form-buttons">
  <%= f.submit("Update Section") %>
</div>
<% end %>

<div class="action index">
  <br/>
<%= link_to("Back to sections", sections_path(page_id: @page.id)) %>
</div>

assignment_1_simple_cms_blueprint/app/views/sections/index.html.erb
<h1>Sections List:</h1>
<br/>

<table>
  <tr>
    <th>Sr No.</th>
    <th>Page id</th>
    <th>Section Name</th>
    <th>Position</th>
    <th>Visible</th>
    <th>Content Type</th>
    <th>Content</th>
    <th>Actions</th>
  </tr>
  <% @sections.each do |section| %>
  <tr>
    <td><%=section.id %></td>
    <td><%= link_to(section.page_id, page_path(section.page_id, subject_id:@page.subject_id)) %></td>
    <td><%=section.name %></td>
    <td><%=section.position %></td>
    <td><%=section.visible ? "Yes" : "No"  %></td>
    <td><%=section.content_type %></td>
    <td><%=section.content %></td>
    <td>
      <%= link_to('Show', section_path(section, page_id: @page.id)) %>
      <%= link_to('Edit', edit_section_path(section,page_id: @page.id)) %>
      <%= link_to('Delete', delete_section_path(section, page_id: @page.id)) %>
    </td>
  </tr>
    <% end %>
</table>
<br/>
<div class="action new">
  <%= link_to("Create New Section",new_section_path(page_id: @page.id)) %>
</div>
<br/>
<div class="action list">
  <%= link_to("Back to Pages",pages_path( subject_id: @page.subject_id)) %>
</div>

assignment_1_simple_cms_blueprint/app/views/sections/new.html.erb
<h1>Create new Section</h1>

<%= form_for(@section, url: sections_path(@section, page_id: @page.id)) do |f| %>
<%= render(partial: 'form', locals: {f: f}) %>
<div class="form-buttons">
  <%= f.submit("Create Section") %>
</div>
<% end %>

<div class="action index">
  <br/>
<%= link_to("Back to sections", sections_path(page_id: @page.id)) %>
</div>

assignment_1_simple_cms_blueprint/app/views/sections/show.html.erb
<h1>Show Section:</h1>

<table>
  <tr>
    <th>Section Name</th>
    <td><%= @section.name %> </td>
  </tr>
  <tr>
    <th>Page Id</th>
    <td><%= link_to(@section.page_id,page_path(@section.page_id, subject_id: @page.subject_id)) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= @section.position %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= @section.visible %></td>
  </tr>
  <tr>
    <th>Content Type</th>
    <td><%= @section.content_type %></td>
  </tr>
  <tr>
    <th>Content</th>
    <td><%= @section.content %></td>
  </tr>
</table>

<div class="action index">
  <br/>
<%= link_to("Back to sections", sections_path(page_id: @page.id)) %>
</div>