assignment_1_simple_cms_blueprint/config/routes.rb
Rails.application.routes.draw do


  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  root 'public#about_us'

  get 'public/contact_us'
  get 'access/menu'
  get 'access/login'
  get 'access/logout'
  post 'access/attempt_login'

  resources :subjects do
    member do
      get :delete
    end
  end

#By default delete route is not included , to include it we have to do this
  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get 'delete'
    end
  end

  resources :admin_users , except: [:show] do
    member do
      get 'delete'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

assignment_1_simple_cms_blueprint/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment1SimpleCmsBlueprint</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

assignment_1_simple_cms_blueprint/app/views/layouts/navbar.html.erb
<!--NOTE:  Any instance variable from controller or view is accessible here in layout. -->

<!DOCTYPE html>
<html>
<head>
  <title></title>
  <!-- Adding application.css file as stylesheet-->
  <%= stylesheet_link_tag "application" %>
</head>
<body>
  <!-- NAV BAR: -->
  <ul>
    <li><%= link_to("About Us", root_path) %></li>
    <li><%= link_to("Contact Us", public_contact_us_path) %></li>
    <% if(session[:user_id]) %>
    <li><%= link_to("Subjects", subjects_path) %></li>
    <li><%= link_to("Admin", access_menu_path) %></li>
    <li><%= link_to("Log out", access_logout_path) %></li>
    <% else %>
      <li><%= link_to("Log In", access_login_path) %></li>
      <li><%= link_to("Sign Up", new_admin_user_path) %></li>
    <% end %>

  </ul>
  <!-- NAV BAR: -->

  <br/>
  <% if !flash[:message].blank? %>
  <div class="flash-container">
    <%= flash[:message] %>
  </div>
  <% end %>
  <br/>
  <div class="welcome-user">
  <% if(session[:user_id]) %>
      <span><%="Hey, #{session[:username]}!!" %></span>
  <% end %>
  </div>
   <!-- before yield -->
 <%= yield %>
  <!-- after yield %> -->
  <footer>
    <p>Author: Sumit Titare &copy;</p>
  </footer>
</body>
</html>